import { access, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { EgreterError } from "@egreter/diagnostics";
import type { EgreterProject } from "@egreter/project";
import type { InlineConfig, Plugin } from "vite";

export interface WebTargetOverrides {
  host?: string | boolean;
  port?: number;
  open?: boolean;
}

const GENERATED_DIR = ".egreter/target-web";
const GENERATED_BOOTSTRAP = `${GENERATED_DIR}/bootstrap.js`;
const GENERATED_HTML = `${GENERATED_DIR}/index.html`;

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

function toProjectUrl(root: string, file: string): string {
  const absolute = path.resolve(root, file);
  const relative = path.relative(root, absolute);

  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new EgreterError(
      "E_WEB_FILE_OUTSIDE_PROJECT",
      `Web bootstrap and entry files must be inside the project root: ${file}`,
      absolute
    );
  }

  return "/" + relative.split(path.sep).join("/");
}

function createDefaultHtml(title: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="theme-color" content="#111827" />
    <title>${title}</title>
    <style>
      html, body { margin: 0; width: 100%; min-height: 100%; background: #030712; }
      body { min-height: 100vh; display: grid; place-items: center; overflow: hidden; }
      #game { display: block; width: min(100vw, 562px); max-height: 100vh; touch-action: none; }
    </style>
  </head>
  <body>
    <canvas id="game" aria-label="Egreter game canvas"></canvas>
    <!-- egreter:entry -->
  </body>
</html>
`;
}

function createBootstrapSource(project: EgreterProject): string {
  const web = project.config.targets.web;
  const groups = {
    beforeScripts: web.bootstrap.filter((item) => item.phase === "before-scripts"),
    beforeEntry: web.bootstrap.filter((item) => item.phase === "before-entry"),
    afterEntry: web.bootstrap.filter((item) => item.phase === "after-entry")
  };

  const loaders = (items: typeof web.bootstrap) =>
    items.map((item) => `() => import(${JSON.stringify(toProjectUrl(project.root, item.file))})`).join(",\n  ");

  return `// Generated by @egreter/target-web. Do not edit.
const externalScripts = ${JSON.stringify(web.scripts, null, 2)};

async function runBootstrap(load) {
  const module = await load();
  const initializer = module.default;
  if (typeof initializer === "function") {
    await initializer();
  } else if (initializer && typeof initializer.then === "function") {
    await initializer;
  }
}

async function loadExternalScript(descriptor) {
  if (descriptor.id && document.getElementById(descriptor.id)) {
    return;
  }

  await new Promise((resolve, reject) => {
    const script = document.createElement("script");
    if (descriptor.id) script.id = descriptor.id;
    script.src = descriptor.src;
    script.type = descriptor.type === "module" ? "module" : "text/javascript";
    script.async = descriptor.async ?? false;
    script.defer = descriptor.defer ?? false;
    if (descriptor.crossOrigin !== undefined) script.crossOrigin = descriptor.crossOrigin;
    if (descriptor.integrity) script.integrity = descriptor.integrity;
    if (descriptor.referrerPolicy) script.referrerPolicy = descriptor.referrerPolicy;

    for (const [name, value] of Object.entries(descriptor.attributes ?? {})) {
      script.setAttribute(name, value);
    }

    script.addEventListener("load", resolve, { once: true });
    script.addEventListener(
      "error",
      () => reject(new Error("Unable to load external script: " + descriptor.src)),
      { once: true }
    );

    (descriptor.inject === "body" ? document.body : document.head).appendChild(script);
  });
}

const beforeScripts = [
  ${loaders(groups.beforeScripts)}
];
const beforeEntry = [
  ${loaders(groups.beforeEntry)}
];
const afterEntry = [
  ${loaders(groups.afterEntry)}
];

for (const load of beforeScripts) {
  await runBootstrap(load);
}
for (const script of externalScripts) {
  await loadExternalScript(script);
}
for (const load of beforeEntry) {
  await runBootstrap(load);
}

await import(${JSON.stringify(toProjectUrl(project.root, project.config.entry))});

for (const load of afterEntry) {
  await runBootstrap(load);
}
`;
}

function createHostPlugin(hostFile: string, bootstrapUrl: string, projectRoot: string): Plugin {
  const entryTag = `<script type="module" src="${bootstrapUrl}"></script>`;
  const rootIndex = path.resolve(projectRoot, "index.html");

  const injectEntry = (html: string): string => {
    if (html.includes("<!-- egreter:entry -->")) {
      return html.replace("<!-- egreter:entry -->", entryTag);
    }

    if (html.includes("</body>")) {
      return html.replace("</body>", `  ${entryTag}\n  </body>`);
    }

    return html + "\n" + entryTag + "\n";
  };

  return {
    name: "egreter:web-host",
    configureServer(server) {
      if (path.resolve(hostFile) === rootIndex) {
        return;
      }

      server.middlewares.use(async (request, response, next) => {
        const requestPath = request.url?.split("?")[0];
        if (requestPath !== "/" && requestPath !== "/index.html") {
          next();
          return;
        }

        try {
          const html = await readFile(hostFile, "utf8");
          const transformed = await server.transformIndexHtml("/", html);
          response.statusCode = 200;
          response.setHeader("Content-Type", "text/html; charset=utf-8");
          response.end(transformed);
        } catch (error) {
          next(error as Error);
        }
      });
    },
    transformIndexHtml(html) {
      return injectEntry(html);
    }
  };
}

async function prepareWebHost(project: EgreterProject): Promise<{
  hostFile: string;
  bootstrapFile: string;
}> {
  const generatedRoot = path.join(project.root, GENERATED_DIR);
  await mkdir(generatedRoot, { recursive: true });

  const bootstrapFile = path.join(project.root, GENERATED_BOOTSTRAP);
  await writeFile(bootstrapFile, createBootstrapSource(project));

  const configuredHtml = project.config.targets.web.html;
  let hostFile: string;

  if (typeof configuredHtml === "string") {
    hostFile = path.resolve(project.root, configuredHtml);
    if (!(await exists(hostFile))) {
      throw new EgreterError(
        "E_WEB_HTML_NOT_FOUND",
        `Configured Web host page was not found: ${configuredHtml}`,
        hostFile
      );
    }
  } else if (configuredHtml !== false && await exists(path.join(project.root, "index.html"))) {
    hostFile = path.join(project.root, "index.html");
  } else {
    hostFile = path.join(project.root, GENERATED_HTML);
    const title = path.basename(project.root) || "Egreter";
    await writeFile(hostFile, createDefaultHtml(title));
  }

  return { hostFile, bootstrapFile };
}

export async function createWebViteConfig(
  project: EgreterProject,
  overrides: WebTargetOverrides = {}
): Promise<InlineConfig> {
  const { config, root } = project;
  const publicDir =
    config.assets === false ? false : path.resolve(root, config.assets);
  const { hostFile, bootstrapFile } = await prepareWebHost(project);
  const bootstrapUrl = toProjectUrl(root, bootstrapFile);

  return {
    root,
    configFile: false,
    publicDir,
    clearScreen: false,
    appType: "spa",
    plugins: [createHostPlugin(hostFile, bootstrapUrl, root)],
    server: {
      ...(overrides.host === undefined && config.server.host === undefined
        ? {}
        : { host: overrides.host ?? config.server.host }),
      port: overrides.port ?? config.server.port,
      open: overrides.open ?? config.server.open,
      strictPort: true
    },
    build: {
      outDir: path.resolve(root, config.outDir),
      emptyOutDir: true,
      sourcemap: config.build.sourcemap,
      minify: config.build.minify,
      target: "es2022",
      rollupOptions: {
        input: hostFile
      }
    }
  };
}


async function findHtmlOutputs(directory: string): Promise<string[]> {
  const outputs: string[] = [];
  const entries = await readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      outputs.push(...(await findHtmlOutputs(file)));
    } else if (entry.name.endsWith(".html")) {
      outputs.push(file);
    }
  }

  return outputs;
}

export async function finalizeWebBuild(project: EgreterProject): Promise<void> {
  const outDir = path.resolve(project.root, project.config.outDir);
  const expected = path.join(outDir, "index.html");

  if (await exists(expected)) {
    return;
  }

  const htmlOutputs = await findHtmlOutputs(outDir);
  if (htmlOutputs.length !== 1) {
    throw new EgreterError(
      "E_WEB_HTML_OUTPUT_INVALID",
      `Expected one Web HTML output, found ${htmlOutputs.length}.`,
      outDir
    );
  }

  const source = htmlOutputs[0];
  if (!source) {
    throw new EgreterError(
      "E_WEB_HTML_OUTPUT_MISSING",
      "Web build did not emit an HTML host page.",
      outDir
    );
  }

  await rename(source, expected);
  await rm(path.join(outDir, ".egreter"), { recursive: true, force: true });
}
